name: quantecon
channels:
  - default
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - matplotlib
  - pandas
  - dask
  - numba
  - ipykernel
  - jupyter_server
  - scikit-image
  - scikit-learn
  - scipy
  - yfinance
  - quantecon
  - sympy
  - statsmodels
  - plotly
  - networkx
  - seaborn
  - graphviz
  - openpyxl
  - pip
